title: Free Hosting!
author: WebGenieML
email: contact@webgenie.ml
description: > # this means to ignore newlines until "baseurl:"
WebGenie.ml offers free hosting services that includes PHP and MySQL. There are no forced ads either! Explore the wonderful world of web coding and get free space to play around on. When you're ready to create a serious site, we have a free plan for that as well as several paid plans.

# social links
twitter_username: WebGenieML
github_username:  WebGenieML

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
